version: '3'

services:
  app:
    container_name: wallet-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: wallets-app
    env_file:
        - ./.env
    volumes:
      - .:/var/www
    depends_on:
      - database
  database:
    container_name: wallet-postgres
    image: postgres:15.4-alpine
    env_file:
        - ./.env
    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DOCKER_POSTGRES_PORTS}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  nginx:
    container_name: wallet-nginx
    image: nginx:latest
    env_file:
        - ./.env
    ports:
      - "${DOCKER_NGINX_PORTS}:80" # Порт для Nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
volumes:
  database_data:
